books = [
    {
        "id" : 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "published_year": "2015",
        "page_count": 1234,
        "language": "English",
    },
    {
        "id" : 2,
        "title": "Django By Example",
        "author": "Antonio Melé",
        "published_year": "2016",
        "page_count": 1023,
        "language": "English",
    },
    {
        "id" : 3,
        "title": "The Web Socket Handbook",
        "author": "Alex Diaconu",
        "published_year": "2019",
        "page_count": 3677,
        "language": "English",
    },
    {
        "id" : 4,
        "title": "Head First JavaScript",
        "author": "Hellen Smith",
        "published_year": "2021",
        "page_count": 540,
        "language": "English",
    },
    {
        "id" : 5,
        "title": "Algorithms and Data Structures In Python",
        "author": "Kent D.Lee",
        "published_year": "2021",
        "page_count": 9282,
        "language": "English",
    },
    {
        "id" : 6,
        "title":"Head First HTML5 Programming",
        "author": "Eric T Freeman",
        "published_year": "2012",
        "page_count": 3006,
        "language": "English",
    },
] #this is the acting database
