"""tags table created

Revision ID: bfb5db07773c
Revises: 2056214de975
Create Date: 2025-06-19 22:55:22.795893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfb5db07773c'
down_revision: Union[str, None] = '2056214de975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booktags',
    sa.Column('book_id', sa.UUID(), nullable=False, foreign_key='books.id'),
    sa.Column('tag_id', sa.UUID(), nullable=False, foreign_key='books.id'),
    sa.PrimaryKeyConstraint('book_id', 'tag_id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('booktags')
    # ### end Alembic commands ###
